============================= test session starts ==============================
platform linux -- Python 3.9.7, pytest-6.2.5, py-1.11.0, pluggy-1.0.0
rootdir: /usr/src/app
plugins: cov-3.0.0
collected 0 items / 1 error

==================================== ERRORS ====================================
____________________ ERROR collecting tests/test_groups.py _____________________
ImportError while importing test module '/usr/src/app/tests/test_groups.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/local/lib/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_groups.py:5: in <module>
    from main import app
E   ModuleNotFoundError: No module named 'main'
=========================== short test summary info ============================
ERROR tests/test_groups.py
!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
=============================== 1 error in 1.22s ===============================
